### ISSUE TITLE
Bugsnag 4.0.0 broke error reporting

### ISSUE THREAD

**Issue by vincentwoo** [bugsnag/bugsnag-ruby#284] opened 2016-03-20 09:22 UTC
Post 4.x upgrade, I'm not getting new bugsnag notifications for errors. Scheduling a test message works, but normal errors do not. I see errors as usual in the logs, however:

```
Mar 20 02:12:41 CoderPad app/web.2:  ActionView::Template::Error (undefined method `organization' for nil:NilClass): 
Mar 20 02:12:41 CoderPad app/web.2:      12:       <input id="name-prompt" placeholder="Erlich Bachman"> 
Mar 20 02:12:41 CoderPad app/web.2:      13:       <button id="go" class="btn btn-primary">Go!</button> 
Mar 20 02:12:41 CoderPad app/web.2:      14:  
Mar 20 02:12:41 CoderPad app/web.2:      15:       <% if (org = @pad.user.organization) %> 
Mar 20 02:12:41 CoderPad app/web.2:      16:         <div class="horizontal-separator">or</div> 
Mar 20 02:12:41 CoderPad app/web.2:      17:  
Mar 20 02:12:41 CoderPad app/web.2:      18:         <% session[:previous_url] = request.fullpath %> 
Mar 20 02:12:41 CoderPad app/web.2:    app/views/pads/show.html.erb:15:in `_app_views_pads_show_html_erb___336180408460726354_70203316415320' 
Mar 20 02:12:41 CoderPad app/web.2:    config/initializers/url_sanitizer.rb:25:in `call' 
```

however i do not see a corresponding new entry in my bugsnag dashboard. this is very alarming!

**Comment by kattrali** [comment] 2016-03-23 15:13
Hi @vincentwoo, I'm taking a look and having trouble reproducing the issue. I created an [example Rails 4.2.6 project](https://github.com/bugsnag/bugsnag-ruby/tree/kattrali/view-crash-test/example/rails-42) configured to be run via `rackup` and then throw a similar error when the application index is loaded.

* [Gemfile.lock](https://github.com/bugsnag/bugsnag-ruby/blob/kattrali/view-crash-test/example/rails-42/Gemfile.lock)
* [crashing erb template](https://github.com/bugsnag/bugsnag-ruby/blob/kattrali/view-crash-test/example/rails-42/app/views/application/index.html.erb)

Can you provide some additional information such as the Gemfile.lock or perhaps any recently changed dependencies? The Bugsnag gem has no dependencies of its own but maybe its an interaction with something else. There are [few changes](https://github.com/bugsnag/bugsnag-ruby/compare/v3.0.0...v4.0.0) between 3.0.0 and 4.0.0, the major version change being necessary only because of dropping Ruby 1.8 support.

**Comment by kattrali** [comment] 2016-04-05 14:49
Released 4.0.1 with a possible fix for this, closing unless there is additional information.

**Comment by lonre** [comment] 2016-04-12 15:44
4.0.1 still have this issue

**Comment by kattrali** [comment] 2016-04-12 21:12
@lonre Can you send an example of an error or sample application to reproduce the issue to support@bugsnag.com (to avoid publicly posting sensitive information)? Alternately I'm available to chat via IRC in [#bugsnag on freenode](http://webchat.freenode.net?channels=%23bugsnag&uio=d4).

**Comment by lonre** [comment] 2016-04-13 03:27
@kattrali Hi, I have report to support@bugsnag.com, please check that, thanks

**Comment by kattrali** [comment] 2016-04-13 18:17
Thanks, @lonre! The error report revealed the underlying issue. Patching in #291.

**Closed** 2016-04-13 18:30 UTC

**Comment by vincentwoo** [comment] 2016-04-13 22:33
for some reason I can't install 4.0.2, is anyone else having this problem?

```
$ bundle update bugsnag | grep bugsnag
Using bugsnag 4.0.1
```
